version: '3.8'

networks:
  bigdata_network:
    name: ${NETWORK_NAME}
    driver: bridge

services:
  jupyter:
    build: ./jupyter-setup
    container_name: jupyter_notebook
    networks:
      - bigdata_network
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    command: start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''

  zookeeper:
    image: zookeeper:3.8
    container_name: zookeeper
    networks:
      - bigdata_network
    environment:
      - ZOO_MY_ID=1

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    networks:
      - bigdata_network
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://${KAFKA_BROKER}
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
    depends_on:
      - zookeeper
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    networks:
      - bigdata_network
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - namenode_data:/hadoop/dfs/name
      - ./hadoop-init.sh:/hadoop-init.sh
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HDFS_CONF_dfs_replication=1
    command: bash /hadoop-init.sh

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    networks:
      - bigdata_network
    depends_on:
      - namenode
    volumes:
      - datanode_data:/hadoop/dfs/data
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000

  spark-master:
    image: apache/spark:3.5.0
    container_name: spark-master
    networks:
      - bigdata_network
    ports:
      - "8181:8080"
      - "7077:7077"
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master

  spark-worker:
    image: apache/spark:3.5.0
    container_name: spark-worker
    networks:
      - bigdata_network
    environment:
      - SPARK_MASTER=${SPARK_MASTER}
    depends_on:
      - spark-master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker ${SPARK_MASTER}

volumes:
  namenode_data:
  datanode_data:
