version: '3.8'

networks:
  bigdata_network:
    name: ${NETWORK_NAME}
    driver: bridge

services:
  jupyter:
    build: ./jupyter-setup
    container_name: jupyter_notebook
    networks:
      - bigdata_network
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    command: start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''

  zookeeper:
    image: zookeeper:3.8
    container_name: zookeeper
    networks:
      - bigdata_network
    environment:
      - ZOO_MY_ID=1

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    networks:
      - bigdata_network
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://${KAFKA_BROKER}
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
    depends_on:
      - zookeeper
