version: '3.8'

networks:
  bigdata_network:
    external: true
    name: ${NETWORK_NAME}

services:
  airflow-db:
    image: postgres:13
    container_name: airflow_postgres
    networks:
      - bigdata_network
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - airflow_db_data:/var/lib/postgresql/data

  airflow-webserver:
    build: ./airflow-setup
    container_name: airflow_webserver
    networks:
      - bigdata_network
    depends_on:
      - airflow-db
    ports:
      - "8082:8080"
    volumes:
      - ./dags:/opt/airflow/dags
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-db/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - KAFKA_BROKER=${KAFKA_BROKER}
      - KAFKA_TOPIC=${KAFKA_TOPIC}
      - HDFS_URL=${HDFS_URL}
      - HDFS_USER=${HDFS_USER}
    command: >
      bash -c "airflow db init && airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com 2>/dev/null || true && airflow webserver"

  airflow-scheduler:
    build: ./airflow-setup
    container_name: airflow_scheduler
    networks:
      - bigdata_network
    depends_on:
      - airflow-db
      - airflow-webserver
    volumes:
      - ./dags:/opt/airflow/dags
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-db/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - KAFKA_BROKER=${KAFKA_BROKER}
      - KAFKA_TOPIC=${KAFKA_TOPIC}
      - HDFS_URL=${HDFS_URL}
      - HDFS_USER=${HDFS_USER}
    command: scheduler

volumes:
  airflow_db_data:
