version: '3.8'

networks:
  bigdata_network:
    name: ${NETWORK_NAME}
    driver: bridge

services:
  jupyter:
    build: ./jupyter-setup
    container_name: jupyter_notebook
    networks:
      - bigdata_network
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    command: start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''
