version: '3.8'

networks:
  bigdata_network:
    external: true

services:
  airflow-db:
    image: postgres:13
    container_name: airflow_postgres
    networks: [ bigdata_network ]
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow

  airflow-webserver:
    build: ./airflow-setup
    container_name: airflow_webserver
    networks: [ bigdata_network ]
    depends_on: [ airflow-db ]
    ports:
      - "8082:8080"
    volumes:
      - ./dags:/opt/airflow/dags
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-db/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    command: >
      bash -c "airflow db init && airflow users create --username admin --firstname admin --lastname admin --role Admin --email admin@example.com --password admin && airflow webserver"

  airflow-scheduler:
    build: ./airflow-setup
    container_name: airflow_scheduler
    networks: [ bigdata_network ]
    depends_on: [ airflow-db ]
    volumes:
      - ./dags:/opt/airflow/dags
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-db/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    command: scheduler
